### ISSUE TITLE
Error when running code. Might be a version issue.

### ISSUE THREAD

**Issue by danielwilczak101** [OneMelon8/TetrisAI#1]
Hey everyone,

Love the YouTube video and project you guys made. I was just trying to run your code and got this error.

```
pygame 2.0.1 (SDL 2.0.14, Python 3.8.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Hello world!
>> Initializing 40 Tetris games in parallel with a grid of 4×10...
>> Screen size calculated to 1410×850...
>> Initializing 40 Tetris agent(s)...
>> Initialization complete! Let the show begin!
Traceback (most recent call last):
  File "TetrisParallel.py", line 326, in <module>
    update(display_screen)
  File "TetrisParallel.py", line 99, in update
    draw(screen)
  File "TetrisParallel.py", line 163, in draw
    draw_text(f">> Agg Height: {AGENTS[agent_index].weight_height:.1f}", screen, (curr_x, curr_y))
AttributeError: 'GeneticAgent' object has no attribute 'weight_height'
```

This might be a version error. Do you have a specific version of pygame or python to run your code?

**Comment by OneMelon8** [comment]
Hello, I'm glad you enjoyed our workshop!

The `GeneticAgent` class is merely a template to follow along with the live coding section in the video. The `GeneticAgentComplete` class has the completed code. To run the code without following along, try changing the `GeneticAgent()` to `GeneticAgentComplete()` when initializing agents (`TetrisParallel.py` at line #321).

![image](https://user-images.githubusercontent.com/48169582/106492367-b3293580-646c-11eb-8b55-bc41486b217a.png)

The definition of `GeneticAgentComplete()` class can be found here:
https://github.com/OneMelon8/TetrisAI/blob/master/TetrisAgents.py#L142

Regarding specific versions of Python/PyGame, we haven't tested it on all the versions, but the version that worked for us is Python 3.7 and PyGame 1.9+

**Comment by danielwilczak101** [comment]
Thank you for clearing that up. It did work and it looks great! I was wondering one thing though. We would love to showcase your example of a use of genetic algorithm on our platform. I was wondering if there was anyway you could try to adapt your code into our ga framework. Its called EasyGA. The whole idea is to make genetic algorithms easy for all levels of programmers. If you want to take a look. Here is our wiki [https://github.com/danielwilczak101/EasyGA/wiki](https://github.com/danielwilczak101/EasyGA/wiki). Let us know what you think! Thank you!

**Comment by OneMelon8** [comment]
I'm glad that helped. Feel free to use this project as an example for your EasyGA platform.
